# 梯度下降算法

In [36]:
# 导入工具包
import tensorflow as tf
import numpy as np

In [37]:
# 实例化SGD
opt = tf.keras.optimizers.SGD(learning_rate=0.1)
# 定义要更新的参数
var = tf.Variable(np.asarray([1.0,2.0,3.0]))
# 定义损失函数
loss = lambda:(var**2)/2.0
# 计算损失梯度，并进行参数更新
opt.minimize(loss,[var]).numpy()
# 参数更新结果
var.numpy()

array([0.9, 1.8, 2.7])

# momentum

In [38]:
# 实例化
opt = tf.keras.optimizers.SGD(learning_rate=0.1,momentum=0.9)
# 定义要更新的参数
var = tf.Variable(1.0)
val0= var.value()
# 定义损失函数
loss = lambda:(var**2)/2.0
# 第一次更新
opt.minimize(loss,[var]).numpy()
val1 = var.value()
# 第二次更新
opt.minimize(loss,[var]).numpy()
val2 = var.value()

In [39]:
val0

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [40]:
val1

<tf.Tensor: shape=(), dtype=float32, numpy=0.9>

In [41]:
val2

<tf.Tensor: shape=(), dtype=float32, numpy=0.71999997>

In [42]:
val0-val1

<tf.Tensor: shape=(), dtype=float32, numpy=0.100000024>

In [43]:
val1-val2

<tf.Tensor: shape=(), dtype=float32, numpy=0.18>

# adagrad

In [44]:
# 实例化
opt = tf.keras.optimizers.Adagrad(learning_rate=0.1,initial_accumulator_value=0.1,epsilon=1e-06)
# 定义要更新的参数
var = tf.Variable(1.0)
# 定义损失函数
def loss():
    return (var**2)/2.0
# 进行更新
opt.minimize(loss,[var]).numpy()

1

In [45]:
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.90465385>

# RMSprop

In [46]:
# 实例化
opt = tf.keras.optimizers.RMSprop(learning_rate=0.1,rho=0.1)
# 定义要更新的参数
var = tf.Variable(1.0)
# 定义损失函数
def loss():
    return (var**2)/2.0
# 进行更新
opt.minimize(loss,[var]).numpy()
var.numpy()

0.89459074

# Adam

In [47]:
# 实例化
opt = tf.keras.optimizers.Adam(learning_rate=0.1)
# 定义要调整的参数
var = tf.Variable(1.0)
# 定义损失函数
def loss():
    return (var**2)/2.0
# 进行更新
opt.minimize(loss,[var])
# 显示结果
var.numpy()

0.90000033